# Generated by Django 5.1.1 on 2024-09-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('AGE', models.CharField(max_length=50)),
                ('CONTACT', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=250)),
                ('USERNAME', models.CharField(max_length=150)),
                ('CATEGORY', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='docters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('AGE', models.CharField(max_length=50)),
                ('CONTACT', models.IntegerField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=250)),
                ('USERNAME', models.CharField(max_length=150)),
                ('CATEGORY', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('AGE', models.CharField(max_length=50)),
                ('CONTACT', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=250)),
                ('USERNAME', models.CharField(max_length=150)),
                ('CATEGORY', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('AGE', models.IntegerField(max_length=50)),
                ('CONTACT', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=250)),
                ('USERNAME', models.CharField(max_length=150)),
                ('CATEGORY', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('AGE', models.CharField(max_length=50)),
                ('CONTACT', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=250)),
                ('USERNAME', models.CharField(max_length=150)),
                ('CATEGORY', models.CharField(max_length=50)),
            ],
        ),
    ]
