# Generated by Django 5.1.1 on 2024-09-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_booking_password_remove_docters_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='CATEGORY',
            new_name='GENDER',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='USERNAME',
        ),
    ]
